GET http://localhost:3003/players/

###
GET http://localhost:3003/players/1/

###
PUT http://localhost:3003/players/2/
Content-Type: application/json

{
  "playerName": "Raju"
}

###
GET http://localhost:3003/matches/1/

###
GET http://localhost:3003/players/9/matches

###
GET http://localhost:3003/matches/1/players

###
GET http://localhost:3003/players/1/playerScores